"""Checks which goals in a goals .pkl are exactly reachable with the Clifford+T gate set.

Every n-qubit gate in the gate set has determinant in the cyclic group generated by
omega^(2^(n-1)) (omega = exp(i pi/4)), and the only global phases that keep matrix entries
in the Clifford+T ring are powers of omega, which leave the determinant of a 2^n x 2^n
matrix unchanged. So det(goal) outside that group means the goal cannot be synthesized
exactly (without ancillas). E.g. on 3 qubits det must be +1 or -1: cct (det omega) and
csqrtswap (det i) are unreachable.

Usage: python scripts/check_goals.py <goals.pkl> [--output <reachable_only.pkl>]
"""
import pickle
from argparse import ArgumentParser

import numpy as np

from domains.qcircuit import *


def det_omega_power(U: np.ndarray) -> int:
    """det(U) as a power of omega = exp(i pi/4), modulo 8"""
    return int(round((np.angle(np.linalg.det(U)) / (np.pi / 4)) % 8)) % 8


def is_reachable(U: np.ndarray) -> bool:
    num_qubits = int(np.log2(U.shape[0]))
    step = 2 ** (num_qubits - 1)  # generator determinants are omega^(k * step)
    return det_omega_power(U) % min(step, 8) == 0


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('input', type=str)
    parser.add_argument('--output', type=str, default=None, help='write only the reachable goals here')
    args = parser.parse_args()

    data = pickle.load(open(args.input, 'rb'))
    keep = []
    for i, goal in enumerate(data['goals']):
        ok = is_reachable(goal.unitary)
        print(f"{i}: det = omega^{det_omega_power(goal.unitary)} -> {'reachable' if ok else 'NOT reachable'}")
        if ok:
            keep.append(i)
    print(f"{len(keep)}/{len(data['goals'])} reachable")

    if args.output is not None:
        out = {k: [v[i] for i in keep] for k, v in data.items()}
        pickle.dump(out, open(args.output, 'wb'))
        print(f"wrote {len(keep)} goals to {args.output}")
